### ISSUE TITLE
Z80 DMA NMOS and CMOS PLCC-44, D5 and D6 reversed

### ISSUE THREAD

**Issue by lynchaj** [flypie/Z80-CPU-for-KiCAD#1]
Hi,  Thank you for posting this very helpful symbol library.

I just found out that in Zilog_Z80_Peripherals symbol library that pins D5 and D6 are reversed on the Z80 DMA PLCC-44 chips.

Per the datasheet, pin 32 is D6 and pin 33 is D5 not the other way around.

I thought you might like to know this and update your symbol library

[Z84C10_Zilog DMA.pdf](https://github.com/flypie/Z80-CPU-for-KiCAD/files/12380256/Z84C10_Zilog.DMA.pdf)

Have a nice day and Thank you.  Andrew Lynch

**Comment by flypie** [comment]
Hi Andrew,

I've fixed that. I think. In the process, the Library has changed from the old format to the new.

**Comment by lynchaj** [comment]
HiAwesome, Thank you.  I must have an old copy pre-fix.  Regardless, Thank you for posting this very nice library.
Excellent work and much appreciated by us Z80 fans!  Thanks! Andrew Lynch
    On Friday, August 18, 2023 at 12:03:01 PM EDT, flypie ***@***.***> wrote:  
 
 


Hi Andrew,

I've fixed that. I think. In the process, the Library has changed from the old format to the new.
